sonar.organization=esavkur
sonar.projectKey=esavkur_wonderlearn
sonar.projectName=WonderLearn

sonar.sources=client/src,server/src
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.pdf,server/public/books/**